apiVersion: v1
kind: ConfigMap
metadata:
  name: client-a-config
  namespace: client-a
data:
  ENDPOINT_NAME_V1: "credit-xgboost-endpoint"
  ENDPOINT_NAME_V2: ""
  TRAFFIC_WEIGHT_V1: "100"
  MODEL_VERSION_V1: "v1"
  MODEL_VERSION_V2: "v2"
  AWS_DEFAULT_REGION: "us-west-2"
  LOG_LEVEL: "INFO"
  MODEL_TYPE: "xgboost"
  TEAM_NAME: "client-a-financial-services"
