apiVersion: v1
kind: Service
metadata:
  name: park-clustering-api-svc
  namespace: client-b
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: park-clustering-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
